DB = "state_db"
TABLE_NAME = "history"
STATE_COLUMN = "state"
ID_COLUMN = "id"

STATES_LIST = "states"
ACTIONS_LIST = "actions"
SCORES_LIST = "scores"

SHOW_DATABASE = "SHOW DATABASES"
SHOW_TABLES = "SHOW TABLES"
SELECT_ALL_DATA = "SELECT * FROM {}".format(TABLE_NAME)
SELECT_GAME_ID = "SELECT id FROM {}".format(TABLE_NAME)

INSERT_DATA = "INSERT INTO {} ({}, {}) VALUES (%s, %s)".format(TABLE_NAME, ID_COLUMN, STATE_COLUMN)


CREATE_DB = "CREATE DATABASE {}".format(DB)
CREATE_TABLE = "CREATE TABLE {}" \
               "(id INT AUTO_INCREMENT NOT NULL PRIMARY KEY, state JSON)".format(TABLE_NAME)

DROP_DB = "DROP DATABASE {}".format(DB)
DROP_TABLE = "DROP TABLE {}".format(TABLE_NAME)

